language: go

go:
  - 1.9.x

install:
  - go get github.com/asasmoyo/sharelatex2git/cmd/sharelatex2git

script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "Arba Sasmoyo"
  - sharelatex2git -e $EMAIL -p $PASSWORD -u $URL --git-url https://$GITHUB_TOKEN@$GITHUB_REPO
