language: go

go:
  - 1.11.x

install:
  - go get -u -v github.com/asasmoyo/overleaf2git/cmd/overleaf2git

script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "Arba Sasmoyo"
  - overleaf2git -s $OVERLEAF_SESSION_KEY -u $URL -git-url https://asasmoyo:$GITHUB_TOKEN@$GITHUB_REPO
